### PR TITLE
Use an ES6 class instead of a factory function

### PR DESCRIPTION
**Pull request by dputtick**
Breaks backwards compatibility, due to no longer supporting access token config via environment variable.

cc/ @drboyer

### CODE REVIEW

**Comment by vsmart** [comment]
👋 @dputtick @drboyer what else is needed here before we can merge and release?

**Comment by drboyer** [comment]
We were waiting for a downstream tool that uses this module to be finalized so that we could capture any other changes that were needed. I observed a few small error handling changes we should make, but we could either include them here or merge and release this and hit them after, I think.

**Comment by drboyer** [comment]
In 29ce2ffdd35c3988ce7d20d9246b01f6fc3a9e98, I changed the format of HTTP errors returned to be simple JSON strings instead of doing any parsing, which should alleviate the issues seen in #8.

**Comment by dputtick** [comment]
@drboyer I think this probably ready to go out, right? Trying to think if there are any other breaking changes we might anticipate needing to make.

**Comment by drboyer** [comment]
Yeah I think this should be okay to 🚢

**Pull request merged**
